Market\SymfonyBundle\Entity\Bookmark:
    type: entity
    table: bookmark
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
         markets:
             targetEntity: Markets
             mappedBy: bookmark
    fields:
        bookmarkName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: bookmark_name
    lifecycleCallbacks: {  }
