<?php

namespace Market\SymfonyBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * DatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatesRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllDatesCurrentDate($product, $resultName)
     {
		$result=$this->getEntityManager()
             ->createQuery(
			'SELECT d FROM MarketSymfonyBundle:Dates d WHERE d.market = :market AND d.marketDate > :time  ORDER BY d.marketDate ASC'
			)->setParameters(array(
				'market' => $product->getId(),
				'time' => date("Y/m/d"),
			))->setFirstResult($resultName)
             ->getResult();
        return $result;
     }

     public function findFirstMarketDate($product)
     {
		$result=$this->getEntityManager()
             ->createQuery(
			'SELECT d FROM MarketSymfonyBundle:Dates d WHERE d.market = :market AND d.marketDate > :time  ORDER BY d.marketDate ASC'
			)->setParameters(array(
				'market' => $product->getId(),
				'time' => date("Y/m/d"),
			))->setMaxResults(1)
             ->getResult();
            if(!isset($result[0])){
            	$result='noResult';
       		}
        return $result;
     }
}
