<?php

namespace Market\SymfonyBundle\Entity;

/**
 * MarketNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketNameRepository extends \Doctrine\ORM\EntityRepository
{
}
