<?php

namespace Market\SymfonyBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * MarketsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketsRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllDatesSelectedMarket($seekedMarket)
    {
		$result=$this->getEntityManager()
            ->createQuery(
			'SELECT m FROM MarketSymfonyBundle:Markets m WHERE m.bookmark = :bookmark ORDER BY m.marketCity ASC'
			)->setParameters(array(
				'bookmark' => $seekedMarket,
			))->getResult();
        return $result;
    }
}
