market_symfony_homepage:
    path:     /hello/{name}
    defaults: { _controller: MarketSymfonyBundle:Default:index }

name_new:
    path:     /form
    defaults: { _controller: MarketSymfonyBundle:Default:new }

showMarketDetails:
    path:     /terminarz/{seekedMarket}
    defaults: { _controller: MarketSymfonyBundle:Markets:showMarket }

